
package views;

import models.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class FrmMain extends javax.swing.JFrame {

    //Instancio la clase DBConnect.
    DBConnect con = new DBConnect();
    
    public FrmMain() {
        initComponents();

        //Asigno en el label que la conexión se estableció.
        LblConecct.setText("Conexión: Establecida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnDataLoad = new javax.swing.JButton();
        LblConecct = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de contactos");
        setResizable(false);

        BtnDataLoad.setText("Cargar Datos");
        BtnDataLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataLoadActionPerformed(evt);
            }
        });

        LblConecct.setText("Conexión: ");

        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Documento", "Nombre completo", "Correo", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShow.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblShow);
        tblShow.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblShow.getColumnModel().getColumnCount() > 0) {
            tblShow.getColumnModel().getColumn(0).setMinWidth(30);
            tblShow.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblShow.getColumnModel().getColumn(0).setMaxWidth(30);
            tblShow.getColumnModel().getColumn(1).setMinWidth(60);
            tblShow.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblShow.getColumnModel().getColumn(1).setMaxWidth(60);
            tblShow.getColumnModel().getColumn(2).setMinWidth(100);
            tblShow.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblShow.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LblConecct)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 288, Short.MAX_VALUE)
                        .addComponent(BtnDataLoad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BtnDataLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblConecct)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDataLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataLoadActionPerformed
        //Instancio el modelo de la tabla
        DefaultTableModel tblContact = new DefaultTableModel();
            
        //Creo el array para alimentar la tabla
        String []contacts = new String[5];
        //Creamos encabezados de la tabla
        tblContact.addColumn("It");
        tblContact.addColumn("Documento");
        tblContact.addColumn("Nombre completo");
        tblContact.addColumn("Correo");
        tblContact.addColumn("Celular");
            
        try {
            //Creo y ejecuto la consulta SQL
            Statement stm = con.getConnection().createStatement();
            ResultSet rs = stm.executeQuery("SELECT document, fullname, email, smartphone FROM people");

            //Valido si se trae información
            int it = 1;
            while (rs.next()) {
                contacts[0] = Integer.toString(it);
                contacts[1] = rs.getString("document");
                contacts[2] = rs.getString("fullname");
                contacts[3] = rs.getString("email");
                contacts[4] = rs.getString("smartphone");
                tblContact.addRow(contacts);
                it++;
            }
            //Agrego las filas a mi modelo de tabla.
            tblShow.setModel(tblContact);
            
            //Ajustamos los anchos de la tabla
            tblShow.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblShow.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblShow.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblShow.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblShow.getColumnModel().getColumn(4).setPreferredWidth(80);
            
            //Inhabilito el boton de carga.
            BtnDataLoad.setEnabled(false);
                    
        } catch (SQLException e) {
            //Si hay algún error
            LblConecct.setText("Conexión: Error " + e);
            
        }
    }//GEN-LAST:event_BtnDataLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDataLoad;
    private javax.swing.JLabel LblConecct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblShow;
    // End of variables declaration//GEN-END:variables
}
