
package views;

// Importamos las clases que requerimos para nuestra aplicación.
import controllers.CtrlContacts;
import models.Contacts;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmStart extends javax.swing.JFrame {

    // Instanciamos el controlador que trabaja con este formulario.
    CtrlContacts c = new CtrlContacts();
    
    /**
     * Creates new form FrmStart
     */
    public FrmStart() {
        initComponents();
        
        // Cuando carga el formulario también cargamos los contactos en la Tabla.
        dataTable();
        startBtn();
        // Si se pobla la tabla muestra Conexión: Establecida
        LblConnect.setText("Conexión: Establecida...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        LblDocument = new javax.swing.JLabel();
        LblFullname = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblSmartphone = new javax.swing.JLabel();
        TxtDocument = new javax.swing.JTextField();
        TxtSmartphone = new javax.swing.JTextField();
        TxtFullname = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        BtnSave = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblShow = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        LblConnect = new javax.swing.JLabel();
        LblIdContact = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        MnuMain = new javax.swing.JMenuBar();
        MnuFile = new javax.swing.JMenu();
        MnuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de contactos");
        setResizable(false);

        LblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitle.setForeground(new java.awt.Color(0, 204, 0));
        LblTitle.setText("Sistema de gestión de contactos");

        LblDocument.setText("Documento: ");

        LblFullname.setText("Nombre completo: ");

        LblEmail.setText("Correo electrónico: ");

        LblSmartphone.setText("Celular:");

        TxtDocument.setEnabled(false);

        TxtSmartphone.setEnabled(false);

        TxtFullname.setEnabled(false);

        TxtEmail.setEnabled(false);

        BtnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSave.setText("Nuevo");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnUpdate.setText("Modificar");
        BtnUpdate.setEnabled(false);
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDelete.setText("Eliminar");
        BtnDelete.setEnabled(false);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        TblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Documento", "Nombre completo", "Correo electrónico", "Celular"
            }
        ));
        TblShow.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TblShowFocusGained(evt);
            }
        });
        TblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TblShowMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TblShow);

        LblConnect.setText("Conexión: ");

        LblIdContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblIdContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIdContact.setText("0");

        BtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCancel.setText("Cancelar");
        BtnCancel.setEnabled(false);
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        MnuFile.setText("Archivo");

        MnuLogout.setText("Salir");
        MnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLogoutActionPerformed(evt);
            }
        });
        MnuFile.add(MnuLogout);

        MnuMain.add(MnuFile);

        setJMenuBar(MnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblIdContact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblDocument)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblSmartphone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtSmartphone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblFullname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCancel)))
                                .addGap(0, 8, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTitle)
                    .addComponent(LblIdContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDocument)
                    .addComponent(LblSmartphone)
                    .addComponent(TxtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSmartphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFullname)
                    .addComponent(TxtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDelete)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnSave)
                    .addComponent(BtnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblConnect)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se encarga de poblar la tabla con los contactos.
     */
    private void dataTable() {
        ArrayList<Contacts> contacts = c.getContacts();
        DefaultTableModel mdlTable = new DefaultTableModel();
        
        mdlTable.addColumn("Id");
        mdlTable.addColumn("It");
        mdlTable.addColumn("Documento");
        mdlTable.addColumn("Nombre completo");
        mdlTable.addColumn("Correo electrónico");
        mdlTable.addColumn("Celular");
        
        TblShow.setModel(mdlTable);
        int it = 1;
        for (Contacts item : contacts) {
            Object[] itemTabla = new Object[6];
            itemTabla[0] = item.getId();
            itemTabla[1] = it;
            itemTabla[2] = item.getDocument();
            itemTabla[3] = item.getFullname();
            itemTabla[4] = item.getEmail();
            itemTabla[5] = item.getSmartphone();
            mdlTable.addRow(itemTabla);
            it++;
        }
        
        TblShow.setModel(mdlTable);
        
        TblShow.getColumnModel().getColumn(0).setMaxWidth(0);
        TblShow.getColumnModel().getColumn(0).setMinWidth(0);
        TblShow.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        TblShow.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        
        TblShow.getColumnModel().getColumn(1).setPreferredWidth(20);
        TblShow.getColumnModel().getColumn(2).setPreferredWidth(80);
        TblShow.getColumnModel().getColumn(3).setPreferredWidth(100);
        TblShow.getColumnModel().getColumn(4).setPreferredWidth(100);
        TblShow.getColumnModel().getColumn(5).setPreferredWidth(80);
    }

    /**
     * Este método se encarga de restablecer al inicio el formulario.
     */
    private void startBtn() {
        TxtDocument.setText("");
        TxtFullname.setText("");
        TxtEmail.setText("");
        TxtSmartphone.setText("");
        TxtDocument.setEnabled(false);
        TxtFullname.setEnabled(false);
        TxtEmail.setEnabled(false);
        TxtSmartphone.setEnabled(false);
        BtnSave.setText("Nuevo");
        BtnSave.setEnabled(true);
        BtnUpdate.setText("Modificar");
        BtnUpdate.setEnabled(false);
        BtnDelete.setText("Eliminar");
        BtnDelete.setEnabled(false);
        BtnCancel.setText("Cancelar");
        BtnCancel.setEnabled(false);
        TblShow.clearSelection();
        LblIdContact.setText("0");
        BtnSave.requestFocus();
    }
    
    /**
     * Este método termina la aplicación.
     * @param evt No implementado
     */
    private void MnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuLogoutActionPerformed

    /**
     * Método que se encarga de guardar los datos en la base de datos.
     * @param evt No implementado.
     */
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        if (BtnSave.getText().equals("Nuevo")) {
            TxtDocument.setEnabled(true);
            TxtFullname.setEnabled(true);
            TxtEmail.setEnabled(true);
            TxtSmartphone.setEnabled(true);
            BtnSave.setText("Guardar");
            BtnCancel.setEnabled(true);
            TxtDocument.requestFocus();
        } else {
            // Falta implementar validación de campos.
            
            // Si los campos estan validados y son true debe guardar el contacto.
            Contacts contact = new Contacts(
                    TxtDocument.getText(),
                    TxtFullname.getText(),
                    TxtEmail.getText(),
                    TxtSmartphone.getText()
            );
            if (c.saveContact(contact)) {
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");
                dataTable();
                startBtn();
                
            } else {
                JOptionPane.showMessageDialog(null, "El registro NO se guardo. Intente de nuevo.");
                
            }
            
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TblShowFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TblShowFocusGained
        
    }//GEN-LAST:event_TblShowFocusGained

    /**
     * Este método se encarga de obtener la información de la tabla para posiblemente editar.
     * @param evt Evento de mouse presionado, obtiene fila (row)
     */
    private void TblShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblShowMousePressed
        int row = TblShow.rowAtPoint(evt.getPoint());
        TxtDocument.setText(String.valueOf(TblShow.getValueAt(row, 2)));
        TxtFullname.setText(String.valueOf(TblShow.getValueAt(row, 3)));
        TxtEmail.setText(String.valueOf(TblShow.getValueAt(row, 4)));
        TxtSmartphone.setText(String.valueOf(TblShow.getValueAt(row, 5)));
        
        LblIdContact.setText(String.valueOf(TblShow.getValueAt(row, 0)));
        
        BtnSave.setEnabled(false);
        BtnUpdate.setEnabled(true);
        BtnDelete.setEnabled(true);
        BtnCancel.setEnabled(true);
    }//GEN-LAST:event_TblShowMousePressed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        //Eliminar registro
        int id = Integer.parseInt(LblIdContact.getText());
        if (c.deleteContact(id)) {
            JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.");
                
        } else {
            JOptionPane.showMessageDialog(null, "El registro NO se eliminó. Intente de nuevo.");
                
        }
        
        dataTable();
        startBtn();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        if (BtnUpdate.getText().equals("Modificar")) {
            //Activar modificacion
            TxtDocument.setEnabled(true);
            TxtFullname.setEnabled(true);
            TxtEmail.setEnabled(true);
            TxtSmartphone.setEnabled(true);
            
            BtnUpdate.setText("Actualizar");
            TxtDocument.requestFocus();
        } else {
            // Falta implementar validación de campos.
            
            // Si los campos estan validados y son true debe actualizar el contacto.
            Contacts contact = new Contacts(
                    TxtDocument.getText(),
                    TxtFullname.getText(),
                    TxtEmail.getText(),
                    TxtSmartphone.getText()
            );
            int id = Integer.parseInt(LblIdContact.getText());
            if (c.updateContact(contact, id)) {
                JOptionPane.showMessageDialog(null, "Registro actualizado correctamente.");
                dataTable();
                startBtn();
                
            } else {
                JOptionPane.showMessageDialog(null, "El registro NO se actualizó. Intente de nuevo.");
                
            }
            
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        startBtn();
    }//GEN-LAST:event_BtnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JLabel LblConnect;
    private javax.swing.JLabel LblDocument;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFullname;
    private javax.swing.JLabel LblIdContact;
    private javax.swing.JLabel LblSmartphone;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JMenu MnuFile;
    private javax.swing.JMenuItem MnuLogout;
    private javax.swing.JMenuBar MnuMain;
    public javax.swing.JTable TblShow;
    private javax.swing.JTextField TxtDocument;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFullname;
    private javax.swing.JTextField TxtSmartphone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
